[package]
name = "test-trustlined-client"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
trustline-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
trustline-sdk = { workspace = true, features = ["testutils"] }
mock-validation-engine = { path = "../mock-validation-engine" }
protected-counter = { path = "../protected-counter" }
